name: Lucuma Steward

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  steward:
    runs-on: ubuntu-latest
    name: Scala Steward
    steps:
      - uses: sbt/setup-sbt@v1
    
      - uses: actions/checkout@v5
          
      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ vars.APP_ID }}
          private_key: ${{ secrets.LUCUMA_STEWARD_PRIVATE_KEY }}

      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          author-email: 106720676+lucuma-steward[bot]@users.noreply.github.com
          author-name: lucuma-steward[bot]
          github-app-id: ${{ vars.APP_ID}}
          github-app-installation-id: ${{ vars.APP_INSTALLATION_ID}}
          github-app-key: ${{ secrets.LUCUMA_STEWARD_PRIVATE_KEY }}
